# Generated by Django 3.1 on 2021-08-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('number_of_Seats', models.IntegerField(default=0)),
                ('rem', models.CharField(max_length=5, null=True)),
                ('fare', models.CharField(max_length=6, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='adminapp.admin')),
            ],
        ),
    ]
