# Generated by Django 3.1 on 2021-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
