# Generated by Django 3.1.7 on 2021-08-03 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
