# Generated by Django 3.1.7 on 2021-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverapp', '0002_auto_20210805_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
