# Generated by Django 3.1 on 2021-08-07 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '__first__'),
        ('driverapp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('kitale', 'Kitale'), ('eldoret', 'Eldoret'), ('kisumu', 'Kisumu')], max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, choices=[('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('kericho', 'Kericho')], max_length=30, null=True)),
                ('seat_no', models.CharField(max_length=30, null=True)),
                ('number_of_Seats', models.IntegerField(default=0)),
                ('fare', models.CharField(max_length=6, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='adminapp.admin')),
                ('busid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='driverapp.bus')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
