# Generated by Django 3.1 on 2021-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
