# Generated by Django 3.1.7 on 2021-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
