# Generated by Django 3.1.7 on 2021-08-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210804_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.buscategory'),
        ),
    ]
