# Generated by Django 3.1.7 on 2021-08-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20210804_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_category',
        ),
    ]
