# Generated by Django 3.1.7 on 2021-08-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_bus_bus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='userapp.buscategory'),
        ),
    ]
